theme: jekyll-theme-minimal
title: M. Eli Bostian
description:  
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
  - title: PZA uptake
    url: pza
  - title: NIZ uptake
    url: niz
